#url:
#baseurl:

styles_path:           /styles/
scripts_path:          /scripts/
images_path:           /images/
slideshow_delay:       5000

exclude: [temp"]
timezone: America/Toronto
future: true
strict_front_matter: true
